from enum import Enum

class Terminals(Enum):
    IF = 'if'
    EOF = 'eof'
    INT = 'int'
    ELSE = 'else'
    CHAR = 'char'
    WHILE = 'while'
    FLOAT = 'float'
    STRUCT = 'struct'
    ADD_EQ = 'add_eq'
    SUB_EQ = 'sub_eq'
    MUL_EQ = 'mul_eq'
    DIV_EQ = 'div_eq'
    STRING = 'string'
    NUMBER = 'number'
    EQUALS = 'equals'
    COMMENT = 'comment'
    SEMICOLON = 'semicolon'
    IDENTIFIER = 'identifier'
    LEFT_CURLY = 'left_curly'
    LEFT_PAREN = 'left_paren'
    RIGHT_PAREN = 'right_paren'
    RIGHT_CURLY = 'right_curly'
    GREATER_THAN = 'greater_than'
